Repository Jaedong2Fanclub/mungpy-spring, pull requests merged in 2024-12, with the labels that each got.

#6 Feat: 동물 등록 기능 추가
  build.gradle
  src/main/java/com/jaefan/munpyspring/animalRegistration/application/AnimalService.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/domain/model/Breed.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/domain/model/ProtectionStatus.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/domain/model/PublicAnimal.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/domain/model/PublicAnimalImage.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/domain/repository/AnimalRepository.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/presentation/AnimalController.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/presentation/dto/PublicAnimalRegistRequestDto.java
  src/main/java/com/jaefan/munpyspring/common/config/S3Config.java
  src/main/java/com/jaefan/munpyspring/common/exception/GlobalExceptionHandler.java
  src/main/java/com/jaefan/munpyspring/common/util/S3Uploader.java
  src/main/java/com/jaefan/munpyspring/signUp/domain/model/Shelter.java
  src/main/java/com/jaefan/munpyspring/signUp/domain/model/User.java
Labels: 기능 추가, 환경 설정

#9 Feat: 동물 등록 기능 추가 & Refactor : 프로젝트 구조 변경
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/jaefan/munpyspring/animal/application/AnimalCrawlingService.java
  src/main/java/com/jaefan/munpyspring/animal/application/AnimalRegistrationService.java
  src/main/java/com/jaefan/munpyspring/animal/application/util/AnimalConverter.java
  src/main/java/com/jaefan/munpyspring/animal/domain/model/AnimalGender.java
  src/main/java/com/jaefan/munpyspring/animal/domain/model/AnimalNeutered.java
  src/main/java/com/jaefan/munpyspring/animal/domain/model/AnimalType.java
  src/main/java/com/jaefan/munpyspring/animal/domain/model/Breed.java
  src/main/java/com/jaefan/munpyspring/animal/domain/model/CrawlingCategory.java
  src/main/java/com/jaefan/munpyspring/animal/domain/model/ProtectionAnimal.java
  src/main/java/com/jaefan/munpyspring/animal/domain/model/ProtectionStatus.java
  src/main/java/com/jaefan/munpyspring/animal/domain/model/PublicAnimal.java
  src/main/java/com/jaefan/munpyspring/animal/domain/model/PublicAnimalImage.java
  src/main/java/com/jaefan/munpyspring/animal/domain/repository/ProtectionAnimalRepository.java
  src/main/java/com/jaefan/munpyspring/animal/domain/repository/PublicAnimalRepository.java
  src/main/java/com/jaefan/munpyspring/animal/presentation/AnimalCrawlingController.java
  src/main/java/com/jaefan/munpyspring/animal/presentation/AnimalRegistrationController.java
  src/main/java/com/jaefan/munpyspring/animal/presentation/dto/AnimalRegistrationDto.java
  src/main/java/com/jaefan/munpyspring/common/config/AppConfig.java
  src/main/java/com/jaefan/munpyspring/common/util/S3Uploader.java
  src/main/java/com/jaefan/munpyspring/common/web/HealthCheckController.java
  src/main/java/com/jaefan/munpyspring/shelter/domain/model/Shelter.java
  src/main/java/com/jaefan/munpyspring/shelter/domain/repository/ShelterRepository.java
  src/main/java/com/jaefan/munpyspring/user/domain/model/User.java
  src/test/java/com/jaefan/munpyspring/MunpySpringApplicationTests.java
Labels: 구조 변경, 기능 추가

#13 Remove: 엔티티 디렉토리 구조 변경에 따른 불필요한 디렉토리 삭제 및 S3 비활성화
  src/main/java/com/jaefan/munpyspring/animalRegistration/application/AnimalService.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/domain/model/Breed.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/domain/model/ProtectionStatus.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/domain/model/PublicAnimal.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/domain/model/PublicAnimalImage.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/domain/repository/AnimalRepository.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/presentation/AnimalController.java
  src/main/java/com/jaefan/munpyspring/animalRegistration/presentation/dto/PublicAnimalRegistRequestDto.java
  src/main/java/com/jaefan/munpyspring/common/config/S3Config.java
  src/main/java/com/jaefan/munpyspring/common/util/S3Uploader.java
  src/main/java/com/jaefan/munpyspring/signUp/domain/model/Shelter.java
  src/main/java/com/jaefan/munpyspring/signUp/domain/model/User.java
Labels: 구조 변경, 환경 설정
