Repository Jaedong2Fanclub/mungpy-spring, pull requests merged in 2025-05, with the labels that each got.

#29 실종 동물 DTO 수정 및 회원가입 중복 이메일 유저 조회 기능 추가
  src/main/java/com/jaefan/munpyspring/animal/application/AnimalRegistrationService.java
  src/main/java/com/jaefan/munpyspring/animal/domain/model/PublicAnimal.java
  src/main/java/com/jaefan/munpyspring/animal/domain/repository/BreedRepository.java
  src/main/java/com/jaefan/munpyspring/animal/presentation/dto/AnimalRegistrationDto.java
  src/main/java/com/jaefan/munpyspring/shelter/domain/repository/ShelterRepository.java
  src/main/java/com/jaefan/munpyspring/user/application/UserService.java
  src/main/java/com/jaefan/munpyspring/user/presentation/UserController.java
Labels: 리팩토링, 기능 추가

#30 feat: 누락되었던 기능들 추가
  src/main/java/com/jaefan/munpyspring/animal/application/AnimalSearchService.java
  src/main/java/com/jaefan/munpyspring/animal/domain/model/ProtectionAnimal.java
  src/main/java/com/jaefan/munpyspring/animal/domain/model/ProtectionAnimalImage.java
  src/main/java/com/jaefan/munpyspring/animal/domain/repository/ProtectionAnimalRepositoryCustom.java
  src/main/java/com/jaefan/munpyspring/animal/domain/repository/ProtectionAnimalRepositoryImpl.java
  src/main/java/com/jaefan/munpyspring/animal/presentation/AnimalController.java
  src/main/java/com/jaefan/munpyspring/common/config/SchedulerConfig.java
  src/test/java/com/jaefan/munpyspring/animal/AnimalServiceTest.java
  src/test/java/com/jaefan/munpyspring/region/RegionServiceTest.java
Labels: 기능 추가, 버그 수정

#31 Feat: 보호동물 채팅 기능 구현
  build.gradle
  src/main/java/com/jaefan/munpyspring/chat/application/ChatService.java
  src/main/java/com/jaefan/munpyspring/chat/domain/ChatMessage.java
  src/main/java/com/jaefan/munpyspring/chat/domain/ChatRoom.java
  src/main/java/com/jaefan/munpyspring/chat/domain/repository/ChatMessageRepository.java
  src/main/java/com/jaefan/munpyspring/chat/domain/repository/ChatRoomRepository.java
  src/main/java/com/jaefan/munpyspring/chat/event/ChatMessageSavedEvent.java
  src/main/java/com/jaefan/munpyspring/chat/event/handler/ChatMessageEventHandler.java
  src/main/java/com/jaefan/munpyspring/chat/messaging/MessageController.java
  src/main/java/com/jaefan/munpyspring/chat/messaging/MessageListener.java
  src/main/java/com/jaefan/munpyspring/chat/messaging/RabbitConstant.java
  src/main/java/com/jaefan/munpyspring/chat/messaging/RabbitMqClient.java
  src/main/java/com/jaefan/munpyspring/chat/presentation/ChatController.java
  src/main/java/com/jaefan/munpyspring/chat/presentation/dto/ChatEnterDto.java
  src/main/java/com/jaefan/munpyspring/chat/presentation/dto/ChatMessageDto.java
  src/main/java/com/jaefan/munpyspring/chat/presentation/dto/ChatRoomDto.java
  src/main/java/com/jaefan/munpyspring/common/config/RabbitConfig.java
  src/main/java/com/jaefan/munpyspring/common/config/WebSecurityConfig.java
  src/main/java/com/jaefan/munpyspring/common/config/WebSocketConfig.java
Labels: 기능 추가, 환경 설정
